name: git push into another repo to deploy to vercel

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3  
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
         - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Ensuring compatibility with Node.js 20
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: jinnyleeis
          destination-repository-name: next-netflix-19th-deploy
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: master
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
